### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by KaterynaToporkova** [KaterynaToporkova/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by TomashKhamlai** [comment]
### DONALD TRUMP
* https://www.fb.com/DonaldTrump
* realDonaldTrump@whitehouse.gov
* https://twitter.com/realDonaldTrump
* https://www.instagram.com/realDonaldTrump/

**Comment by KaterynaToporkova** [comment]
<h3>DONALD TRUMP</h3>

<a href="https://www.fb.com/DonaldTrump">Facebook</a>
<a href="mailto:realDonaldTrump@whitehouse.gov">Mail</a>
<a href="https://twitter.com/realDonaldTrump">Twitter</a>
<a href="https://www.instagram.com/realDonaldTrump/">Instagram</a>
